/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author estef
 */
public class AgregarHabitats1 extends javax.swing.JFrame {

    /**
     * Creates new form AgregarHabitats1
     */
    public AgregarHabitats1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bnHabitat = new javax.swing.JLabel();
        InputNombreHabi = new javax.swing.JTextField();
        NombreHabitat = new javax.swing.JLabel();
        TipoAmbiente = new javax.swing.JLabel();
        InputTipoAmbi = new javax.swing.JTextField();
        Capacidad = new javax.swing.JLabel();
        InputCapacidad = new javax.swing.JTextField();
        InputTemperatura = new javax.swing.JTextField();
        Temperatura = new javax.swing.JLabel();
        GuardarHabi = new javax.swing.JButton();
        MenuHabi = new javax.swing.JButton();
        AtrasHabi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        bnHabitat.setForeground(new java.awt.Color(51, 51, 51));
        bnHabitat.setText("Ingrese los datos del Habitat");

        InputNombreHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreHabiActionPerformed(evt);
            }
        });

        NombreHabitat.setText("Nombre");

        TipoAmbiente.setText("Tipo Ambiente");

        InputTipoAmbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTipoAmbiActionPerformed(evt);
            }
        });

        Capacidad.setText("Capacidad");

        InputCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCapacidadActionPerformed(evt);
            }
        });

        InputTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTemperaturaActionPerformed(evt);
            }
        });

        Temperatura.setText("Temperatura");

        GuardarHabi.setBackground(new java.awt.Color(102, 102, 102));
        GuardarHabi.setForeground(new java.awt.Color(255, 255, 255));
        GuardarHabi.setText("Guardar");
        GuardarHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarHabiActionPerformed(evt);
            }
        });

        MenuHabi.setBackground(new java.awt.Color(102, 102, 102));
        MenuHabi.setForeground(new java.awt.Color(255, 255, 255));
        MenuHabi.setText("Menu");
        MenuHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHabiActionPerformed(evt);
            }
        });

        AtrasHabi.setBackground(new java.awt.Color(102, 102, 102));
        AtrasHabi.setForeground(new java.awt.Color(255, 255, 255));
        AtrasHabi.setText("Atras");
        AtrasHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasHabiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InputTemperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                            .addComponent(Temperatura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputCapacidad, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Capacidad)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InputNombreHabi, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                                .addComponent(NombreHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TipoAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InputTipoAmbi)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GuardarHabi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AtrasHabi)
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(bnHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(MenuHabi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bnHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(NombreHabitat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputNombreHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoAmbiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputTipoAmbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Capacidad)
                .addGap(12, 12, 12)
                .addComponent(InputCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Temperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarHabi)
                    .addComponent(AtrasHabi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(MenuHabi)
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasHabiActionPerformed
        RegistroDeHabitats atrasHabi = new RegistroDeHabitats();
        atrasHabi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasHabiActionPerformed

    private void MenuHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHabiActionPerformed
        RegistroDeHabitats menuHabi = new RegistroDeHabitats ();
        menuHabi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuHabiActionPerformed

    private void GuardarHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarHabiActionPerformed

    }//GEN-LAST:event_GuardarHabiActionPerformed

    private void InputTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTemperaturaActionPerformed
        String HabitatAni = InputCapacidad.getText();
    }//GEN-LAST:event_InputTemperaturaActionPerformed

    private void InputCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCapacidadActionPerformed
        String especieAni = InputCapacidad.getText();
    }//GEN-LAST:event_InputCapacidadActionPerformed

    private void InputTipoAmbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTipoAmbiActionPerformed
        String edadAni = InputTipoAmbi.getText();
    }//GEN-LAST:event_InputTipoAmbiActionPerformed

    private void InputNombreHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreHabiActionPerformed
        String nombreAni = InputNombreHabi.getText();
        JOptionPane.showMessageDialog(null, nombreAni);
    }//GEN-LAST:event_InputNombreHabiActionPerformed
                     

                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarHabitats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarHabitats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarHabitats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarHabitats1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarHabitats1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasHabi;
    private javax.swing.JLabel Capacidad;
    private javax.swing.JButton GuardarHabi;
    private javax.swing.JTextField InputCapacidad;
    private javax.swing.JTextField InputNombreHabi;
    private javax.swing.JTextField InputTemperatura;
    private javax.swing.JTextField InputTipoAmbi;
    private javax.swing.JButton MenuHabi;
    private javax.swing.JLabel NombreHabitat;
    private javax.swing.JLabel Temperatura;
    private javax.swing.JLabel TipoAmbiente;
    private javax.swing.JLabel bnHabitat;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
